version: "1.0"
info:
  model: int-scaffold
packages:
- name: Pratibha1Project
  gitServerName: PT
  gitUrl: https://github.com/Pratibha24/Pratibha1Project
  gitUsername: Pratibha24
  gitBranch: main
- name: TestRepo1
  gitServerName: PT
  gitUrl: https://github.com/Pratibha24
  gitUsername: Pratibha24
  gitBranch: main
